version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    command: "python -m bot"
    env_file:
      - .env
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: "python -m uvicorn api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
